name: eden_work_sample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ably_flutter: ^1.2.22
  cupertino_icons: ^1.0.6
  envied: ^0.5.1
  font_awesome_flutter: ^10.6.0
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^2.4.6
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  go_router: ^12.1.1 
  google_sign_in: ^6.1.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  overlay_support: ^2.1.0
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  envied_generator: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
